version: "3.10"

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro

  api_ipam:
    image: mz/ipam_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DB_NAME: ${DB_NAME}
      DB_PASSWD: ${DB_PASSWD}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - postgres
